
name: GitHub Actions CI

on: 
  push:
    branches: 
    - develop
  pull_request:
    branches: 
    - develop

jobs:

  linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          ubuntu20-gcc9-openmpi
        ]
        include:
        - jobname: ubuntu20-gcc9-openmpi
          container: 
            image: williamfgc/qmcpack-ci:ubuntu20-openmpi
            options: -u user

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1

    - name: Configure
      run: config/github-actions/ci/run_step.sh configure

    - name: Build
      run: config/github-actions/ci/run_step.sh build

    - name: Test
      run: config/github-actions/ci/run_step.sh test

